base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about-me/', views.AboutMe.as_view(), name='about'),
    path('talk-to-me/', views.ContactMe.as_view(), name='contact'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('base.urls', namespace='base')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pass

project/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

class AboutMe(TemplateView):
    template_name = 'about.html'


class ContactMe(TemplateView):
    template_name = 'contact.html'

project/views.py
from django.shortcuts import render

# Create your views here.

base/templates/about.html
{% extends 'partials/_layout.html' %}
{% load static %}
{% block title %}About Me{% endblock title %}
{% block content %}
<section class="about-area">
    <div class="container">
        <div class="d-flex about-me-wrap align-items-start gap-24">
            <div data-aos="zoom-in">
                <div class="about-image-box shadow-box">
                    <img src="{% static 'images/bg1.png' %}" alt="BG" class="bg-img">
                    <div class="image-inner">
                        <img src="{% static 'images/me2.png' %}" alt="About Me">
                    </div>
                </div>
            </div>

            <div class="about-details" data-aos="zoom-in">
                <h1 class="section-heading" data-aos="fade-up"><img src="{% static 'images/star-2.png' %}" alt="Star"> Self-summary <img src="{% static 'images/star-2.png' %}" alt="Star"></h1>
                <div class="about-details-inner shadow-box">
                    <img src="{% static 'images/icon2.png' %}" alt="Star">
                    <h1>Oluwaseun Matanmi</h1>
                    <p>I am a San francisco-based product designer with a focus on web design, illustration, a visual development. I have a diverse range of experience having worked across various fields and industries.</p>
                </div>

            </div>
        </div>

        <div class="row mt-24">
            <div class="col-md-6" data-aos="zoom-in">
                <div class="about-edc-exp about-experience shadow-box">
                    <img src="{% static 'images/bg1.png' %}" alt="BG" class="bg-img">
                    <h3>EXPERIENCE</h3>

                    <ul>
                        <li>
                            <p class="date">2007 - 2017</p>
                            <h2>Framer Designer & Developer</h2>
                            <p class="type">Bluebase Designs</p>
                        </li>
                        <li>
                            <p class="date">2017 - 2023</p>
                            <h2>Front-End Developer</h2>
                            <p class="type">Larsen & Toubro</p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6" data-aos="zoom-in">
                <div class="about-edc-exp about-education shadow-box">
                    <img src="{% static 'images/bg1.png' %}" alt="BG" class="bg-img">
                    <h3>EDUCATION</h3>

                    <ul>
                        <li>
                            <p class="date">2004 - 2007</p>
                            <h2>Bachelor Degree in Psychology</h2>
                            <p class="type">University of California</p>
                        </li>
                        <li>
                            <p class="date">2007 - 2009</p>
                            <h2>Master Degree in Designing</h2>
                            <p class="type">University of Texas</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row mt-24">
            <div class="col-md-12">
                <div class="d-flex profile-contact-credentials-wrap gap-24">

                    <div data-aos="zoom-in">
                        <div class="about-profile-box info-box shadow-box h-full">
                            <img src="{% static 'images/bg1.png' %}" alt="BG" class="bg-img">
                            <div class="inner-profile-icons shadow-box">
                                <a href="#">
                                    <i class="iconoir-dribbble"></i>
                                </a>
                                <a href="#">
                                    <i class="iconoir-twitter"></i>
                                </a>
                            </div>
                            <div class="d-flex align-items-center justify-content-between">
                                <div class="infos">
                                    <h4>Stay with me</h4>
                                    <h1>Profiles</h1>
                                </div>

                                <a href="contact.html" class="about-btn">
                                    <img src="{% static 'images/icon.svg' %}" alt="Button">
                                </a>

                            </div>
                        </div>
                    </div>

                    <div data-aos="zoom-in" class="flex-1">
                        <div class="about-contact-box info-box shadow-box">
                            <a class="overlay-link" href="contact.html"></a>
                            <img src="{% static 'images/bg1.png' %}" alt="BG" class="bg-img">
                            <img src="{% static 'images/icon2.png' %}" alt="Icon" class="star-icon">
                            <h1>Let's <br>work <span>together.</span></h1>
                            <a href="contact.html" class="about-btn">
                                <img src="{% static 'images/icon.svg' %}" alt="Button">
                            </a>
                        </div>
                    </div>

                    <div data-aos="zoom-in" class="h-full">
                        <div class="about-crenditials-box info-box shadow-box">
                            <a class="overlay-link" href="credentials.html"></a>
                            <img src="{% static 'images/bg1.png' %}" alt="BG" class="bg-img">
                            <img src="{% static 'images/sign.png' %}" alt="Sign">
                            <div class="d-flex align-items-center justify-content-between">
                                <div class="infos">
                                    <h4>more about me</h4>
                                    <h1>Credentials</h1>
                                </div>

                                <a href="credentials.html" class="about-btn">
                                    <img src="{% static 'images/icon.svg' %}" alt="Button">
                                </a>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

base/templates/contact.html
{% extends 'partials/_layout.html' %}
{% load static %}
{% block title %}Let's talk{% endblock title %}
{% block content %}
<section class="contact-area">
    <div class="container">
        <div class="gx-row d-flex justify-content-between gap-24">
            <div class="contact-infos">
                <h3 data-aos="fade-up">Contact Info</h3>
                <ul class="contact-details">
                    <li class="d-flex align-items-center" data-aos="zoom-in">
                        <div class="icon-box shadow-box">
                            <i class="iconoir-mail"></i>
                        </div>
                        <div class="right">
                            <span>MAIL us</span>
                            <h4>info@bluebase.com</h4>
                            <h4>info@bluebase2.com</h4>
                        </div>
                    </li>

                    <li class="d-flex align-items-center" data-aos="zoom-in">
                        <div class="icon-box shadow-box">
                            <i class="iconoir-phone"></i>
                        </div>
                        <div class="right">
                            <span>Contact Us</span>
                            <h4>+1 504-899-8221</h4>
                            <h4>+1 504-749-5456</h4>
                        </div>
                    </li>

                    <li class="d-flex align-items-center" data-aos="zoom-in">
                        <div class="icon-box shadow-box">
                            <i class="iconoir-pin-alt"></i>
                        </div>
                        <div class="right">
                            <span>Location</span>
                            <h4>22 Baker Street, Texas <br>United States <br>W1U 3BW</h4>
                        </div>
                    </li>
                </ul>

                <h3 data-aos="fade-up">Social Info</h3>
                <ul class="social-links d-flex align-center" data-aos="zoom-in">
                    <li><a class="shadow-box" href="#"><i class="iconoir-dribbble"></i></a></li>
                    <li><a class="shadow-box" href="#"><i class="iconoir-twitter"></i></a></li>
                    <li><a class="shadow-box" href="#"><i class="iconoir-instagram"></i></a></li>
                </ul>
            </div>

            <div data-aos="zoom-in" class="contact-form">
                <div class="shadow-box">
                    <img src="{% static 'images/bg1.png' %}" alt="BG" class="bg-img">
                    <img src="{% static 'images/icon3.png' %}" alt="Icon">
                    <h1>Let’s work <span>together.</span></h1>
                    <form method="POST" action="https://wpriverthemes.com/landing/gridx-html/mailer.php">
                        <div class="alert alert-success messenger-box-contact__msg" style="display: none" role="alert">
                            Your message was sent successfully.
                        </div>
                        <div class="input-group">
                            <input type="text" name="full-name" id="full-name" placeholder="Name *">
                        </div>
                        <div class="input-group">
                            <input type="email" name="email" id="email" placeholder="Email *">
                        </div>
                        <div class="input-group">
                            <input type="text" name="subject" id="subject" placeholder="Your Subject *">
                        </div>
                        <div class="input-group">
                            <textarea name="message" id="message" placeholder="Your Message *"></textarea>
                        </div>
                        <div class="input-group">
                            <button class="theme-btn submit-btn" name="submit" type="submit">Send Message</button>
                        </div>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</section>
{% endblock content %}

base/templates/index.html
{% extends 'partials/_layout.html' %}
{% load static %}
{% block title %}Matanmi Oluwaseun{% endblock title %}
{% block content %}
<!-- About -->
<section class="about-area">
    <div class="container">
        <div class="row">
            <div class="col-md-6" data-aos="zoom-in">
                <div class="about-me-box shadow-box">
                    <a class="overlay-link" href="about.html"></a>
                    <img src="{% static 'images/bg1.png' %}" alt="BG" class="bg-img">
                    <div class="img-box">
                        <img src="{% static 'images/me.png' %}" alt="About Me">
                    </div>
                    <div class="infos">
                        <h4>A WEB DESIGNER</h4>
                        <h1>David Henderson.</h1>
                        <p>I am a Web Designer based in san francisco.</p>
                        <a href="#" class="about-btn">
                            <img src="{% static 'images/icon.svg' %}" alt="Button">
                        </a>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="about-credentials-wrap">
                    <div data-aos="zoom-in">
                        <div class="banner shadow-box">
                            <div class="marquee">
                                <div>
                                    <span>LATEST WORK AND <b>FEATURED</b> <img src="{% static 'images/star1.svg' %}"
                                            alt="Star"> LATEST WORK AND <b>FEATURED</b> <img
                                            src="assets/images/star1.svg" alt="Star"> LATEST WORK AND <b>FEATURED</b>
                                        <img src="assets/images/star1.svg" alt="Star"> LATEST WORK AND <b>FEATURED</b>
                                        LATEST WORK AND <img src="assets/images/star1.svg" alt="Star"> LATEST WORK AND
                                        <b>FEATURED</b> LATEST WORK AND <img src="assets/images/star1.svg"
                                            alt="Star"></span>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="gx-row d-flex gap-24">
                        <div data-aos="zoom-in">
                            <div class="about-crenditials-box info-box shadow-box h-full">
                                <a class="overlay-link" href="credentials.html"></a>
                                <img src="{% static 'images/bg1.png' %}" alt="BG" class="bg-img">
                                <img src="{% static 'images/sign.png' %}" alt="Sign">
                                <div class="d-flex align-items-center justify-content-between">
                                    <div class="infos">
                                        <h4>more about me</h4>
                                        <h1>Credentials</h1>
                                    </div>

                                    <a href="credentials.html" class="about-btn">
                                        <img src="{% static 'images/icon.svg' %}" alt="Button">
                                    </a>

                                </div>
                            </div>
                        </div>

                        <div data-aos="zoom-in">
                            <div class="about-project-box info-box shadow-box h-full">
                                <a class="overlay-link" href="works.html"></a>
                                <img src="{% static 'images/bg1.png' %}" alt="BG" class="bg-img">
                                <img src="{% static 'images/my-works.png' %}" alt="My Works">
                                <div class="d-flex align-items-center justify-content-between">
                                    <div class="infos">
                                        <h4>SHOWCASE</h4>
                                        <h1>Projects</h1>
                                    </div>

                                    <a href="#" class="about-btn">
                                        <img src="{% static 'images/icon.svg' %}" alt="Button">
                                    </a>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-24">
            <div class="col-md-6" data-aos="zoom-in">

                <div class="about-client-box info-box shadow-box">
                    <img src="{% static 'images/bg1.png' %}" alt="BG" class="bg-img">
                    <div class="clients d-flex align-items-start gap-24 justify-content-center">
                        <div class="client-item">
                            <h1>07</h1>
                            <p>Years <br>Experience</p>
                        </div>

                        <div class="client-item">
                            <h1>+125</h1>
                            <p>CLIENTS <br>WORLDWIDE</p>
                        </div>

                        <div class="client-item">
                            <h1>+210</h1>
                            <p>Total <br>Projects</p>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-6" data-aos="zoom-in">

                <div class="about-contact-box info-box shadow-box">
                    <a class="overlay-link" href="contact.html"></a>
                    <img src="{% static 'images/bg1.png' %}" alt="BG" class="bg-img">
                    <img src="{% static 'images/icon2.png' %}" alt="Icon" class="star-icon">
                    <h1>Let's <br>work <span>together.</span></h1>
                    <a href="#" class="about-btn">
                        <img src="{% static 'images/icon.svg' %}" alt="Button">
                    </a>
                </div>

            </div>
        </div>
    </div>
</section>
{% endblock content %}

base/templates/partials/_footer.html
{% load static %}
<footer class="footer-area">
    <div class="container">
        <div class="footer-content text-center">
            <a href="{% url 'base:index' %}" class="logo">
                <img src="{% static 'images/logo.svg' %}" alt="Logo">
            </a>
            <ul class="footer-menu">
                <li><a href="{% url 'base:index' %}">Home</a></li>
                <li><a href="{% url 'base:about' %}">About</a></li>
                <li><a href="works.html">Works</a></li>
                <li><a href="{% url 'base:contact' %}">Contact</a></li>
            </ul>
            <p class="copyright">
                &copy; All rights reserved by <span>WordPress River</span>
            </p>
        </div>
    </div>
</footer>

base/templates/partials/_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    {% include 'partials/_stylesheet.html' %}
</head>
<body>

    <main class="main-homepage">

        <!-- Header -->
        {% include 'partials/_navbar.html' %}
        <!-- Content -->
        {% block content %}

        {% endblock content %}
        <!-- Footer -->
        {% include 'partials/_footer.html' %}

    </main>

    {% include 'partials/_script.html' %}
</body>
</html>

base/templates/partials/_navbar.html
{% load static %}
<header class="header-area">
    <div class="container">
        <div class="gx-row d-flex align-items-center justify-content-between">
            <a href="{% url 'base:index' %}" class="logo">
                <img src="{% static 'images/logo.svg' %}" alt="Logo">
            </a>
            <nav class="navbar">
                <ul class="menu">
                    <li class="active"><a href="{% url 'base:index' %}">Home</a></li>
                    <li><a href="{% url 'base:about' %}">About</a></li>
                    <li><a href="works.html">Works</a></li>
                </ul>
                <!-- <a href="contact.html" class="theme-btn">Let's talk</a> -->
            </nav>

            <a href="{% url 'base:contact' %}" class="theme-btn">Let's talk</a>

            <div class="show-menu">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
</header>

base/templates/partials/_script.html
{% load static %}
<script src="{% static 'js/jquery-3.6.4.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

base/templates/partials/_stylesheet.html
{% load static %}
<!-- Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com/">
<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800&amp;display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/iconoir.css' %}">

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/aos.cs' %}">

<link rel="stylesheet" href="{% static 'css/style.css' %}">

base/templates/work-details.html
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from wpriverthemes.com/landing/gridx-html/work-details.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 15 Apr 2023 05:31:08 GMT -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gridx - Personal Portfolio HTML Template</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800&amp;display=swap" rel="stylesheet">

    <link rel="stylesheet" href="../../../cdn.jsdelivr.net/gh/iconoir-icons/iconoir%40main/css/iconoir.css">

    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/aos.css">

    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>

    <main class="main-workdetails-page">

        <!-- Header -->
        <header class="header-area">
            <div class="container">
                <div class="gx-row d-flex align-items-center justify-content-between">
                    <a href="index.html" class="logo">
                        <img src="assets/images/logo.svg" alt="Logo">
                    </a>

                    <nav class="navbar">
                        <ul class="menu">
                            <li><a href="index.html">Home</a></li>
                            <li><a href="about.html">About</a></li>
                            <li><a href="works.html">Works</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                        <a href="contact.html" class="theme-btn">Let's talk</a>
                    </nav>

                    <a href="contact.html" class="theme-btn">Let's talk</a>

                    <div class="show-menu">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
            </div>
        </header>

        <!-- Breadcrumb -->
        <section class="breadcrumb-area">
            <div class="container">
                <div class="breadcrumb-content" data-aos="fade-up">
                    <p>BRANDING - RAVEN STUDIO</p>
                    <h1 class="section-heading"><img src="assets/images/star-2.png" alt="Star"> Aesthetic design for brand <br>new startup <img src="assets/images/star-2.png" alt="Star"></h1>
                </div>
            </div>
        </section>

        <!-- Project Details -->
        <section class="project-details-wrap">
            <div class="project-details-img" data-aos="zoom-in">
                <img src="assets/images/project-dt-1.jpg" alt="Project Details">
            </div>

            <div class="container">
                <div data-aos="zoom-in">
                    <div class="d-flex project-infos-wrap shadow-box mb-24">
                        <img src="assets/images/bg1.png" alt="BG" class="bg-img">
                        <img src="assets/images/icon2.png" alt="Icon">
                        <div class="project-details-info flex-1">
                            <h3>Raven studio</h3>
                            <p>Sit amet luctussd fav venenatis, lectus magna fringilla inis urna, porttitor rhoncus dolor purus non enim praesent in elementum sahas facilisis leo, vel fringilla est ullamcorper eget nulla facilisi etisam dignissim diam quis enim lobortis viverra orci sagittis eu volutpat odio facilisis mauris sit.</p>
                            <p>Scelerisque fermentum duisi faucibus in ornare quam sisd sit amet luctussd fav venenatis, lectus magna fringilla zac urna, porttitor rhoncus dolor purus non enim praesent cuz elementum sahas facilisis leot.</p>
                        </div>
    
                        <div class="project-details-info flex-1">
                            <h3>About</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna ve fringilla urna, porttitor rhoncus dolor purus nonds enim isi praesent elementum facilisis leo.</p>
                            <p>Vel fringilla est ullamcorper eget nulla facilisi etiama ashfa dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis eu agv he volutpat odio asas facilisis mauris sit.</p>
                        </div>
                    </div>
                </div>

                <div class="project-details-2-img mb-24" data-aos="zoom-in">
                    <img src="assets/images/project-dt-1.jpg" alt="Project">
                </div>

                <div class="row mb-24">
                    <div class="col-md-6" data-aos="zoom-in">
                        <div class="project-details-3-img">
                            <img src="assets/images/project3.jpg" alt="Project">
                        </div>
                    </div>
                    <div class="col-md-6" data-aos="zoom-in">
                        <div class="project-details-3-img">
                            <img src="assets/images/project4.jpg" alt="Project">
                        </div>
                    </div>
                </div>

                <div class="row mb-24">
                    <div class="col-md-6" data-aos="zoom-in">
                        <div class="project-details-3-img">
                            <img src="assets/images/project5.jpg" alt="Project">
                        </div>
                    </div>
                    <div class="col-md-6" data-aos="zoom-in">
                        <div class="project-details-3-img">
                            <img src="assets/images/project6.jpg" alt="Project">
                        </div>
                    </div>
                </div>

                <div data-aos="zoom-in">
                    <div class="project-about-2 d-flex shadow-box mb-24">
                        <img src="assets/images/bg1.png" alt="BG" class="bg-img">
                        <div class="left-details">
                            <img src="assets/images/icon3.png" alt="Icon">
                            <ul>
                                <li>
                                    <p>Year</p>
                                    <h4>2023</h4>
                                </li>
                                <li>
                                    <p>Client</p>
                                    <h4>Raven Studio</h4>
                                </li>
                                <li>
                                    <p>Services</p>
                                    <h4>Web Design</h4>
                                </li>
                                <li>
                                    <p>Project</p>
                                    <h4>Dynamic</h4>
                                </li>
                            </ul>
                        </div>
                        <div class="right-details">
                            <h3>Description</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit utsadi sfejdis aliquam, purus sit amet luctus venenatis, lectus magna sansit trandis fringilla urna, porttitor rhoncus dolor purus non enim dollors praesent tabasi elementum facilisis leo, vel fringilla est ullamcorper eget nulla facilisi etiam facilisis dignissim diam quis enim lobortis scelerisque.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit utsadi sfejdis aliquam, purus sit amet luctus venenatis, lectus magna sansit trandis fringilla urna, porttitor rhoncus dolor purus non enim dollors praesent tabasi elementum facilisis leo, vel fringilla est ullamcorper eget nulla facilisi etiam facilisis dignissim diam quis enim lobortis scelerisque iin fermentumisa dui faucibus in ornare.Lorem ipsum dolor sit.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="project-details-img" data-aos="zoom-in">
                <img src="assets/images/project-dt-1.jpg" alt="Project Details">
            </div>

            <div class="container d-flex align-items-center justify-content-center" data-aos="zoom-in">
                <a href="#" class="big-btn shadow-box">
                    Next Project
                </a>
            </div>
            
        </section>
        
        


        <!-- Footer -->
        <footer class="footer-area">
            <div class="container">
                <div class="footer-content text-center">
                    <a href="index.html" class="logo">
                        <img src="assets/images/logo.svg" alt="Logo">
                    </a>
                    <ul class="footer-menu">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="about.html">About</a></li>
                        <li><a href="works.html">Works</a></li>
                        <li><a href="contact.html">Contact</a></li>
                    </ul>
                    <p class="copyright">
                        &copy; All rights reserved by <span>WordPress River</span>
                    </p>
                </div>
            </div>
        </footer>

    </main>
    

    <script src="assets/js/jquery-3.6.4.js"></script>
    <script src="assets/js/bootstrap.bundle.min.js"></script>
    <script src="assets/js/aos.js"></script>
    <script src="assets/js/main.js"></script>
</body>

<!-- Mirrored from wpriverthemes.com/landing/gridx-html/work-details.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 15 Apr 2023 05:31:09 GMT -->
</html>